site_name: M4MVC
theme: material
pages:
    - 'Introduction': 'index.md'
    - 'Core':
      - 'App': 'core/app.md'
      - 'Controller': 'core/controller.md'
      - 'Model': 'core/model.md'
      - 'Module': 'core/module.md'
    - 'Helpers':
      - 'String': 'helper/string.md'
      - 'Query': 'helper/query.md'
      - 'Redirect': 'helper/redirect.md'
      - 'Request': 'helper/request.md'
markdown_extensions:
  - codehilite
